// <auto-generated />
using System;
using Kash.Elector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kash.Elector.Data.Migrations
{
    [DbContext(typeof(ElectorContext))]
    partial class ElectorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kash.Elector.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ElectionId");

                    b.Property<int?>("ElectoralListId");

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<int>("Seats");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectoralListId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Kash.Elector.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Kash.Elector.Elector", b =>
                {
                    b.Property<string>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<int?>("DistrictId");

                    b.HasKey("CredentialId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Electors");
                });

            modelBuilder.Entity("Kash.Elector.ElectoralList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DistrictId");

                    b.Property<string>("Party")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("ElectoralLists");
                });

            modelBuilder.Entity("Kash.Elector.District", b =>
                {
                    b.HasOne("Kash.Elector.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId");

                    b.HasOne("Kash.Elector.ElectoralList")
                        .WithMany("Districts")
                        .HasForeignKey("ElectoralListId");
                });

            modelBuilder.Entity("Kash.Elector.Elector", b =>
                {
                    b.HasOne("Kash.Elector.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");
                });

            modelBuilder.Entity("Kash.Elector.ElectoralList", b =>
                {
                    b.HasOne("Kash.Elector.District")
                        .WithMany()
                        .HasForeignKey("DistrictId");
                });
#pragma warning restore 612, 618
        }
    }
}
